spring:
  application:
    name: blueprint-iceberg-cdc
  profiles:
    default: changelog

cdcapp:
  aws:
    endpoint: http://localhost:4566
    region: eu-central-1
    access-key-id: admin
    secret-access-key: admin123
  sqs:
    queue-name: flight_tickets.fifo
    poll-delay: 2000
    max-messages: 10
    wait-time-seconds: 10
  kafka:
    bootstrap-servers: localhost:9094
    topic: flight_tickets
    schema-registry-url: http://localhost:8081
  iceberg:
    catalog-uri: http://localhost:8181
    warehouse: s3://analytics-warehouse
    table: rest.default.flight_tickets
    changelog-view: rest.default.flight_tickets_changelog
    s3-endpoint: http://localhost:9000
    s3-region: eu-central-1
    s3-access-key: admin
    s3-secret-key: admin123
  state:
    cursor-file: /tmp/cdcapp.snapshot.cursor

downstreamconsumer:
  kafka:
    bootstrap-servers: localhost:9094
    topic: flight_tickets
    group-id: downstream-consumer
    avro-specific-reader: false
