services:
  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-admin123}
    ports:
      - "9000:9000"
      - "9001:9001"

  minio-init:
    image: amazon/aws-cli
    container_name: minio-init
    command: |
      -c "sleep 2 && \
      aws --endpoint-url http://minio:9000 s3 mb s3://analytics-warehouse --region ${AWS_REGION:-eu-central-1} || exit 0"
    entrypoint: [ /bin/bash ]
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-admin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-admin123}
      AWS_REGION: ${AWS_REGION:-eu-central-1}
    depends_on:
      - minio

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: ${AWS_REGION:-eu-central-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-admin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-admin123}
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on: [minio-init, localstack]
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-admin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-admin123}
      AWS_DEFAULT_REGION: ${AWS_REGION:-eu-central-1}
      AWS_REGION: ${AWS_REGION:-eu-central-1}
    volumes:
      - ./trino/iceberg.properties:/etc/trino/catalog/iceberg.properties:ro
      - ./trino/config.properties:/etc/trino/config.properties

  iceberg-rest-catalog:
    image: apache/iceberg-rest-fixture:latest
    container_name: iceberg-rest-catalog
    depends_on: [minio-init]
    ports:
      - "8181:8181"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-admin}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-admin123}
      AWS_REGION: ${AWS_REGION:-eu-central-1}
      CATALOG_WAREHOUSE: s3://analytics-warehouse
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_PATH__STYLE__ACCESS: "true"
      CATALOG_S3_ACCESS__KEY__ID: ${AWS_ACCESS_KEY_ID:-admin}
      CATALOG_S3_SECRET__ACCESS__KEY: ${AWS_SECRET_ACCESS_KEY:-admin123}


  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: INTERNAL://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    ports:
      - "9092:9092"  
    healthcheck:
      test: ['CMD', '/opt/kafka/bin/kafka-topics.sh', '--bootstrap-server', 'kafka:9092', '--list']
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s

  kafka-schema-registry:
    container_name: kafka-schema-registry
    image: ghcr.io/aiven-open/karapace:4.1.1
    ports:
      - "8081:8081"
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint:
      - /opt/karapace/start.sh
      - registry
    environment:
      KARAPACE_BOOTSTRAP_URI: kafka:9092
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_PORT: 8081

      KARAPACE_ADVERTISED_HOSTNAME: kafka-schema-registry
      KARAPACE_ADVERTISED_PORT: 8081

      KARAPACE_MASTER_ELIGIBILITY: "true"
      KARAPACE_TOPIC_NAME: _schemas
      KARAPACE_AUTHENTICATION: "false"
      KARAPACE_AUTHORIZATION: "false"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8084:8080"
    depends_on:
      kafka:
        condition: service_healthy
      kafka-schema-registry:
        condition: service_started
    environment:
      KAFKA_CLUSTERS_0_NAME: "LocalKafka"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_SCHEMA_REGISTRY: "http://kafka-schema-registry:8081"

  hue:
    image: gethue/hue:latest
    container_name: hue-dev-tool-query-ui
    user: "0:0"
    ports:
      - "8888:8888"
    environment:
      - HUE_DATABASE_ENGINE=sqlite3
      - HUE_IGNORE_PASSWORD_SCRIPT_ERRORS=True
      - TMPDIR=/tmp
    volumes:
      - ./hue:/usr/share/hue/desktop/conf
    depends_on:
      trino:
        condition: service_started
