connector.name=iceberg
iceberg.file-format=parquet
iceberg.catalog.type=glue
iceberg.catalog.warehouse=s3://analytics-warehouse
fs.native-s3.enabled=true

hive.metastore.glue.region=eu-central-1
hive.metastore.glue.endpoint-url=http://localstack:4566

s3.endpoint=http://minio:9000
s3.region=eu-central-1
s3.path-style-access=true
s3.aws-access-key=admin
s3.aws-secret-key=admin123
